name: Publish Production Docker Image to GitHub Container Registry
on:
    push:
        branches:
            - prod
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Create .env file
              working-directory: ./
              run: |
                pwd
                touch .env
                echo NEXT_PUBLIC_NCP_CLIENT_ID=${{ secrets.NCP_CLIENT_ID }}
                cat .env
            - uses: docker/setup-buildx-action@v2
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build Docker Image (ARM64)
              run: |
                docker buildx build --platform linux/arm64 \
                             -t ghcr.io/${{ github.repository }}:latest \
                             -t ghcr.io/${{ github.repository }}:${{ github.sha }} \
                             --load .
            - name: Push Docker Image
              run: |
                docker push ghcr.io/${{ github.repository }}:latest
                docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
